#!/usr/bin/env bash

# dotfiles directory
DOTFILES_DIRECTORY="${HOME}/dotfiles"

download_dotfiles() {
  if [[ ! -d "${DOTFILES_DIRECTORY}" ]]; then
    echo "Downloading dotfiles..."
    # -p Create intermediate directories as required.
    mkdir -p "${DOTFILES_DIRECTORY}"
    # Get the tarball
    if curl -fsSLo ~/dotfiles.tar.gz https://github.com/MarkHershey/dotfiles/tarball/master; then
      echo "Done."
    else
      echo "Failed to download the dotfiles."
      exit 1
    fi
    # Extract to the dotfiles directory
    echo "Extracting the dotfiles..."
    tar -zxf "${HOME}/dotfiles.tar.gz" --strip-components 1 -C "${DOTFILES_DIRECTORY}"
    if [[ -d "${DOTFILES_DIRECTORY}" ]]; then
      echo "Done."
    else
      echo "Failed to extract the dotfiles."
      exit 1
    fi
    # Remove the tarball
    echo "Removing dotfiles.tar.gz..."
    rm ~/dotfiles.tar.gz
    echo "Done."
  fi
}

# download dotfiles
download_dotfiles

echo "Changing directory to ${DOTFILES_DIRECTORY}"
cd "${DOTFILES_DIRECTORY}" || { echo "Failed to change directory." >&2;exit 1; }
echo "Done."

# start install script
./install