#!/usr/bin/env bash

# Ref: https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -euo pipefail
IFS=$'\n\t'


get_opsy() {
    [ -f /etc/redhat-release ] && awk '{print $0}' /etc/redhat-release && return
    [ -f /etc/os-release ] && awk -F'[= "]' '/PRETTY_NAME/{print $3,$4,$5}' /etc/os-release && return
    [ -f /etc/lsb-release ] && awk -F'[="]+' '/DESCRIPTION/{print $2}' /etc/lsb-release && return
}

next() {
    printf "%-70s\n" "-" | sed 's/\s/-/g'
}

OS="xxx"
case $(uname) in
    'Darwin') 
        OS='macOS'
        ;;
    'Linux')
        OS='Linux'
        opsy=$( get_opsy )
        cpu_name=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo | sed 's/^[ \t]*//;s/[ \t]*$//' )
        cores=$( awk -F: '/processor/ {core++} END {print core}' /proc/cpuinfo )
        freq=$( awk -F'[ :]' '/cpu MHz/ {print $4;exit}' /proc/cpuinfo )
        source /etc/lsb-release
        if [[ $DISTRIB_ID == 'Ubuntu' ]]; then
            OS='Ubuntu'
        fi
        ;;
    'FreeBSD')
        OS='FreeBSD'
        ;;
    'WindowsNT')
        OS='Windows'
        ;;
    'SunOS')
        OS='Solaris'
        ;;
    'AIX')
        OS='IBM AIX'
        ;;
    *)
        echo "Aborting: System not identified"
        exit 1
        ;;
esac

echo "System identified: ${OS}"
next

# TODO: general install option on shared public machine
# GENERAL_INSTALL=0

# Parse options
# while [ $# -gt 0 ]; do
# 	case "$1" in
# 	-g) GENERAL_INSTALL=1 ;;
# 	--general) GENERAL_INSTALL=1 ;;
# 	*) echo "Option $1 not recognized" ;;
# 	esac
# 	shift
# done

export TERM=xterm-256color

if [[ $OS == 'macOS' ]]; then
    echo "Setting up dotfiles for macOS..."
    # ./setup_macOS
elif [[ $OS == 'Ubuntu' ]]; then
    echo "Linux Distro      : ${opsy}"
    echo "CPU Model         : ${cpu_name}"
    echo "CPU Cores         : ${cores}"
    echo "CPU Frequency     : ${freq}"
    echo "CPU Architecture  : $(uname -m)"
    next
    echo "Setting up dotfiles for Ubuntu..."
    # ./setup_ubuntu
elif [[ $OS == 'Linux' ]]; then
    echo "Aborting: Setup script is tested for Ubuntu only, it may fail on non-ubuntu Linux distro."
    exit 1
else
    echo "Aborting: OS not supported"
    exit 1
fi