#!/usr/bin/env bash

# reference: https://github.com/anishathalye/dotfiles
# reference: https://github.com/dhruvmanila/dotfiles

# declare integer
declare -i exitcode
exitcode=0

# get base directory
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# # dotfiles directory
# declare DOTFILES_DIRECTORY="${HOME}/dotfiles"
# declare DOTFILES_TARBALL_PATH="https://github.com/MarkHershey/dotfiles/tarball/master"
# declare DOTFILES_GIT_REMOTE="https://github.com/MarkHershey/dotfiles.git"

# source utility functions
source "${BASEDIR}/utils" || { echo "Failed to source utils" >&2;exit 1; }


# ----------------------------------------------------
# zsh 

p_header "Install wget zsh vim git tmux etc..."
{ sudo apt-get remove --assume-yes vim-tiny && \
sudo apt-get update && \
sudo apt-get install -y --no-install-recommends \
wget \
zsh \
vim \
git \
tmux \
tree \
make \
build-essential; } || { echo "Failed" >&2;exit 1; }
p_success "Done"


# ----------------------------------------------------
# default shell

p_header "Change default shell to zsh"
# { chsh -s "$(which zsh)" && echo "$SHELL"; } || { echo "Failed" >&2;exit 1; }
{ sudo chsh ${USER} -s $(which zsh) && echo "${SHELL}"; } || { echo "Failed" >&2;exit 1; }
p_success "Done"

# ----------------------------------------------------
# Oh My ZSH

p_header "Install Oh My ZSH"
if [[ ! -d "${ZSH}" ]]; then
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended || { echo "Failed" >&2;exit 1; }
    p_success "Done"
else
    p_success "Oh My ZSH already installed."
fi

# ----------------------------------------------------
# Zsh Syntax Highlighting

p_header "Install Zsh Syntax Highlighting"
TMP_INSTALL_PATH="${HOME}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
if [[ ! -d "${TMP_INSTALL_PATH}" ]]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${TMP_INSTALL_PATH}" || { echo "Failed" >&2;exit 1; }
    p_success "Done"
else
    p_success "Zsh Syntax Highlighting already installed."
fi

# ----------------------------------------------------
# Powerlevel 10k

p_header "Install Powerlevel 10k"
TMP_INSTALL_PATH="${HOME}/.oh-my-zsh/themes/powerlevel10k"
if [[ ! -d "${TMP_INSTALL_PATH}" ]]; then
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${TMP_INSTALL_PATH}" || { echo "Failed" >&2;exit 1; }
    p_success "Done"
else
    p_success "Powerlevel 10k already installed."
fi

# ----------------------------------------------------
# Vim plugins

p_header "Linking .vim"
ln -s "${BASEDIR}/vim/" ~/.vim || exitcode=1
p_success "Done"



# ----------------------------------------------------
# Linking dotfiles

link_dotfile "zsh/zshrc"       ".zshrc"       || exitcode=1
link_dotfile "p10k/p10k.zsh"   ".p10k.zsh"    || exitcode=1
link_dotfile "tmux/tmux.conf"  ".tmux.conf"   || exitcode=1
link_dotfile "vim/vimrc"       ".vimrc"       || exitcode=1
link_dotfile "vim/"            ".vim"         || exitcode=1
link_dotfile "git/gitconfig"   ".gitconfig"   || exitcode=1



# ----------------------------------------------------
# Exit

if [ ${exitcode} -eq 1 ]; then
    echo "Some parts failed"
else
    p_success "------ All Completed ------"
fi

exit ${exitcode}