name: CI-ubuntu-curl

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Curl Install Script
        run: |
          pwd
          git config credential.https://github.com.username GitHubActions
          set -euo pipefail
          export TERM=xterm-256color
          mkdir TEST && cd TEST
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/MarkHershey/dotfiles/master/curl_install)"